### PR TITLE
Resolve possibility for XSS

### PR DESCRIPTION
**Pull request by avivkeller**
This PR fixes the XSS vulnerability in YARD 0.9.34, by using code from a later version of yard.

### CODE REVIEW

**Comment by avivkeller** [comment]
I have signed the CLA!

**Comment by avivkeller** [comment]
Hey, any update on this?

**Comment by DerekStride** [comment]
I have a couple of concerns:

1. That html file is generated by running [`bundle exec yard`](https://github.com/Shopify/tree_stand/blob/d7f1fa9c7acc01bf77da219ed0ad5cf51da60e3c/.github/workflows/publish_docs.yml#L29) so modifying it a PR will get undone on the next deploy. This should be fixed by updating YARD on the main branch instead.
2. This project has been merged upstream in [`ruby_tree_sitter`](https://github.com/Faveod/ruby-tree-sitter) (see 
https://github.com/Shopify/tree_stand/pull/32) and may suffer from this same issue. That's a better place to apply the fix.

**Comment by avivkeller** [comment]
If this to be deprecated, then this pull really won't help with anything, so your right, and I'll check out the upstream. Thank you for your help. If you want to resolve the issue down here, just update yard to `0.9.36` or higher.

**Pull request closed without merging**
